Add sorting to Asset endpoint
kobotoolbox/kpi pull request #2547
Opened 2020-01-09 22:08 UTC by noliveleger

It's possible to sort by these fields: 
- `asset_type`
- `date_modified`
- `name`
- `owner__username`
- `subscribers_count`

Django default parameter is `ordering` but it can be changed to match `submissions` ordering parameter (i.e. `sort`)

It's also possible to filter by these fields: 
- `settings__country__label`
- `settings__organization`
- `settings__sector_label`
- `summary__languages`

Names have been chosen to respect Django ORM (and Whoosh?) nomenclature (but could be changed) 

## NOT RETRO-COMPATIBLE CHANGE
Before, to get assets without no parents, `parent=` should be passed among querystring parameters. 
It is not the case anymore: 
To (try to) be consistent, it has to be passed as `parent__uid:none` inside `q` parameter. e.g: `q=parent__uid:none` 

## EXAMPLE: 
to retrieve assets with no parents, with type: `collection, block, template` and with languages: `French (fr)` ordered by subscribers_count (desc) , request should like this 

`https://kpi/api/v2/assets/?q=parent__uid:none AND asset_type:collection OR asset_type:block OR asset_type:template AND summary_languages:French (fr)&ordering=-subscribers_count`

2020-05-15 23:37 UTC, noliveleger commented
Search by `summary__language` does not work anymore.
Error:
`Unsupported lookup 'languages' for JSONField or join on the field not permitted`

May be fixed by #2635

2020-09-11 07:30 UTC, jnm requested changes

2020-09-15 20:11 UTC, jnm commented on kpi/filters.py
> +        query_parts = q.split(' AND ')  # Can be risky if one of values contains ` AND `
we've opted to add `status` as its own query parameter (and allow filtering only by one `status` at a time)

2020-09-15 20:17 UTC, jnm commented on kpi/views/v2/asset.py
> +                pass
wrong! `ValueError` is to guard against `None['oops']`

2020-09-15 22:23 UTC, jnm commented on kpi/utils/asset_content_analyzer.py
> +                formatted_translations.append(translation.capitalize())
we've removed `format_translations()` :cry:

2020-09-15 22:30 UTC, jnm approved these changes

2020-09-15 22:47 UTC, merged