Regex checking in header title
kobotoolbox/kpi pull request #2773
Opened 2020-08-27 18:23 UTC by duvld

## Description

Added regex checking to changes in the title to remove invalid characters.

## Related issues

Fixes #2721

2020-09-07 14:03 UTC, magicznyleszek commented
@duvld I think you need to create a small utility function in `jsapp/js/assetUtils.es6` and then use it here (`jsapp/js/components/header.es6`) and in two more places: Project Settings (`jsapp/js/components/modalForms/projectSettings.es6`, also used as modal) and Form Builder (`jsapp/js/editorMixins/editableForm.es6`)

2020-09-07 14:04 UTC, magicznyleszek requested changes
@duvld I think you need to create a small utility function in `jsapp/js/assetUtils.es6` and then use it here (`jsapp/js/components/header.es6`) and in two more places: Project Settings (`jsapp/js/components/modalForms/projectSettings.es6`, also used as modal) and Form Builder (`jsapp/js/editorMixins/editableForm.es6`)

2020-09-08 16:12 UTC, jnm commented
I restarted the Travis build, and hopefully it won't fail again. If it still fails, let's merge `master` into this branch and try again

2020-09-08 16:27 UTC, magicznyleszek requested changes

2020-09-08 16:27 UTC, magicznyleszek commented on jsapp/js/components/modalForms/projectSettings.es6
> +                value={removeInvalidChars(this.state.name)}
Instead of using it here, please use it in `onNameChange` and `onDescriptionChange` (similarly as in `editableForm.es6` below) :heart:

2020-09-16 08:19 UTC, merged