2778 in app messages
kobotoolbox/kpi pull request #2966
Opened 2021-01-21 22:08 UTC by JacquelineMorrissette

## Checklist

1. [x] If you've added code that should be tested, add tests
2. [N/A] If you've changed APIs, update (or create!) the documentation
3. [x] Ensure the tests pass
4. [x] Make sure that your code lints and that you've followed [our coding style](https://github.com/kobotoolbox/kpi/blob/master/CONTRIBUTING.md)
5. [x] Write a description of your work suitable for publishing on [our forum](https://community.kobotoolbox.org/tag/release-notes)
6. [x] Mention any related issues in this repository (as #ISSUE) and in other repositories (as kobotoolbox/other#ISSUE)

## Description

Created a warning for superusers when creating in-app messages.
-This warning is to alert the user that they should drag and drop photos into the snippet and/or body
-The URL from in-app message files takes the user to the right image, but through a path that only superusers can access

## Related issues

Part of #2778

2021-01-28 15:22 UTC, noliveleger requested changes

2021-01-28 15:22 UTC, noliveleger commented on kobo/apps/help/admin.py
> +        #     for warings, a second field set must be set with with the list
typo? `warnings`

2021-01-29 02:11 UTC, JacquelineMorrissette commented on kobo/apps/help/admin.py
> +        #     for warings, a second field set must be set with with the list
fixed!

2021-02-01 21:30 UTC, merged

2021-02-12 07:09 UTC, jnm commented
@JacquelineMorrissette I did a little light editing to the PR text to prepare for publishing at https://community.kobotoolbox.org/c/announcements/7:

* I removed the issue number from the PR title and made the title a little more descriptive;
* I added spaces after the dashes in your list of changes so that they'd be recognized as Markdown bullet points.