Update docs for submission `/edit` endpoint
kobotoolbox/kpi pull request #2993
Opened 2021-02-03 02:20 UTC by joshuaberetta

## Description

Updated documentation for the submission `/edit` endpoint, specifying the addition of the `view_only` parameter to obtain a URL that displays the submission in view-only mode in Enketo's UI.

## Related issues

closes #2992 
part of https://github.com/kobotoolbox/kobocat/issues/671
blocked by https://github.com/kobotoolbox/kobocat/pull/672

2021-02-11 16:05 UTC, noliveleger requested changes

2021-02-11 16:05 UTC, noliveleger commented on jsapp/js/dataInterface.es6
> +    getEnketoViewLink(uid, sid) {
Where can we use this call in the UI?

2021-06-24 20:41 UTC, magicznyleszek requested changes

2021-06-24 20:41 UTC, magicznyleszek commented on jsapp/js/components/submissions/submissionModal.es6
> +    enketoHandler.openSubmission(this.props.asset.uid, this.state.sid, 'edit').then(
Please make `'edit'` and `'view'` a constant defined in `enketoHandler`. I wanted to describe here our way of defining enum-like objects, but ended up improving our ways and there is new PR: kpi#3321. I don't know how much more work you have here, but if the `createEnum` PR is merged first, please use it :)

2021-06-24 20:41 UTC, magicznyleszek commented on jsapp/js/components/submissions/submissionModal.es6
> +                  className='kobo-button kobo-button--blue submission-duplicate__button'
I think when you click it, it should be disabled while loading, so `disabled={this.state.isViewLoading}` :)

2021-06-24 20:41 UTC, magicznyleszek commented on jsapp/js/enketoHandler.es6
> +    let dataInt = dataInterface.getEnketoEditLink;
Please use a bit more descriptive variable name - I thought that `dataInt` is a variable that is a shortcut to `dataInterface`. Maybe `dataIntMethod`?

2021-06-30 10:42 UTC, magicznyleszek approved these changes

2021-07-02 13:41 UTC, noliveleger approved these changes

2021-07-02 13:41 UTC, merged

2021-07-06 06:00 UTC, ahmad1k commented
Hi, can I get these links? I mean previously I was using " https://kc.humanitarianresponse.info/api/v1/data" link
Thanks

2021-07-06 15:22 UTC, joshuaberetta commented
Hi @ahmad1k, this feature has not yet been released into production.