Support export object filtering in API
kobotoolbox/kpi pull request #3011
Opened 2021-02-15 20:08 UTC by joshuaberetta

## Description

Support export object filtering in API by adding the query parameter of `ordering` to the `/exports` endpoint URL.

## Related issues

closes #3010

2021-02-26 19:00 UTC, noliveleger requested changes

2021-02-26 19:20 UTC, joshuaberetta commented on kpi/serializers/v2/export_task.py
> +                    format_exception_values(VALID_BOOLEANS)
Correct 👍 before I refactored the exceptions to use the `format_exception_values` function, there were single quotes inside, but I'll change that.

2021-02-26 22:26 UTC, joshuaberetta commented on kpi/constants.py
> +EXPORT_SETTING_SOURCE = 'source'
Done 👍

2021-02-26 22:40 UTC, joshuaberetta commented on kpi/permissions.py
> +    perms_map['DELETE'] = perms_map['GET']
That's a good point 👍 I'd be in favour of my granular permissions, however I guess the more granular permissions we end up adding the greater chance we have of getting it wrong (I can speak for myself here at least).

@noliveleger, I assume you mean: `DELETE` requires `change_asset` and `POST` requires `view_submissions`?

2021-02-26 22:47 UTC, joshuaberetta commented on kpi/serializers/v2/export_task.py
> +            raise serializers.ValidationError(_('`fields` must be an array'))
Great advice 🙌

2021-02-26 23:33 UTC, joshuaberetta commented on kpi/serializers/v2/export_task.py
> +    @property
You are very correct 👍

2021-03-03 18:02 UTC, joshuaberetta commented on kpi/permissions.py
> +    perms_map['DELETE'] = perms_map['GET']
Ah yes... thanks for picking that up. In my mind it made sense that the export objects themselves were also shared, but I've changed it to have the same behaviour as `v1` 👍

2021-03-05 22:00 UTC, noliveleger approved these changes

2021-03-05 22:00 UTC, merged