Filter `_index` in advanced exports
kobotoolbox/kpi pull request #3334
Opened 2021-07-07 19:31 UTC by joshuaberetta

## Related issues

closes #3333

2021-08-10 13:53 UTC, noliveleger reviewed
Because of a conflict with beta, I merged beta in your branch.
But the tests are not passing. 
> ======== 17 failed, 681 passed ...

Would you mind to look it ?

2021-08-10 13:53 UTC, noliveleger commented on kpi/tests/test_mock_data_exports.py
> +            [ "2017-10-23T05:41:32.000-04:00", "2017-10-23T05:42:05.000-04:00", "Yes" ],
Not a blocker at all, Just a notice that we could remove the leading and trailing spaces in each list ( and use single quotes ;-)). (Several other places in this file too)

2021-08-16 14:48 UTC, noliveleger commented
@joshuaberetta, as per our discussion, 17 tests are failing because it misses some mixes brought to `2.021.30`.
After merging `2.021.30`, only one test fails. This diff makes it pass though:

```diff 
--- a/kpi/tests/test_mock_data_exports.py
+++ b/kpi/tests/test_mock_data_exports.py
@@ -609,9 +609,10 @@ class MockDataExports(MockDataExportsBase):
     def test_xls_export_filter_fields_repeat_groups(self):
         export_options = {
             'fields': [
-                "_uuid",
-                "_submission_time",
-                "person/name",
+                '_uuid',
+                '_submission_time',
+                'person/name',
+                '_index',
             ]
         }
```
         
I would prefer if you could commit these changes (and test them) before I merge your PR.

2021-08-16 14:50 UTC, noliveleger requested changes
@joshuaberetta, as per our discussion, 17 tests are failing because it misses some fixes brought to `2.021.30`.
After merging `2.021.30`, only one test fails. This diff makes it pass though:

```diff 
--- a/kpi/tests/test_mock_data_exports.py
+++ b/kpi/tests/test_mock_data_exports.py
@@ -609,9 +609,10 @@ class MockDataExports(MockDataExportsBase):
     def test_xls_export_filter_fields_repeat_groups(self):
         export_options = {
             'fields': [
-                "_uuid",
-                "_submission_time",
-                "person/name",
+                '_uuid',
+                '_submission_time',
+                'person/name',
+                '_index',
             ]
         }
```
         
I would prefer if you could commit these changes (and test them) before I merge your PR, if you don't mind.

2021-08-16 19:17 UTC, joshuaberetta commented
That was exactly the unpushed fix on my side too 🙃

2021-08-18 14:25 UTC, merged