Users with partial permissions cannot see attachments fix
kobotoolbox/kpi pull request #3404
Opened 2021-08-10 11:59 UTC by noliveleger

## Checklist

1. [ ] If you've added code that should be tested, add tests
2. [ ] If you've changed APIs, update (or create!) the documentation
3. [x] Ensure the tests pass
4. [x] Make sure that your code lints and that you've followed [our coding style](https://github.com/kobotoolbox/kpi/blob/master/CONTRIBUTING.md)
5. [x] Write a description of your work suitable for publishing on [our forum](https://community.kobotoolbox.org/tag/release-notes)
6. [x] Mention any related issues in this repository (as #ISSUE) and in other repositories (as kobotoolbox/other#ISSUE)

## Description

Make users with partial `view_submissions` permission be able to view submission attachments instead of a broken link.

## Additional info

Gallery is temporarily deactivated (for users with partial `view_submissions` permission) until new gallery is released 

## Related issues

Fixes #3389

2021-08-10 12:02 UTC, noliveleger commented
@jnm, @duvld, I have assigned both of you because this PR contains front-end and back-end changes.

2021-11-08 20:02 UTC, jnm requested changes

2021-11-08 20:58 UTC, jnm commented on kpi/deployment_backends/kc_access/shadow_models.py
> +            # to generate the token and let KoBoCAT compare it to its referrer.
https://github.com/kobotoolbox/kpi/issues/3383

2021-11-08 21:34 UTC, noliveleger commented on kpi/deployment_backends/kobocat_backend.py
> +        point to KPI (instead of KoBoCAT). See TBC
`TBC` = To be completed, but it should have been removed since I did a comment ;-)

2021-11-10 19:50 UTC, jnm approved these changes

2021-11-10 19:50 UTC, merged