Fix parsing of submission XML for bulk editing
kobotoolbox/kpi pull request #3648
Opened 2022-01-31 20:01 UTC by joshuaberetta

## Description

Use `lxml.etree` consistently for parsing and editing XML tree.

## Related issues

closes#3647

2022-02-01 21:36 UTC, joshuaberetta commented
Thanks @jnm — done 💪

2022-04-27 21:35 UTC, jnm requested changes

2022-04-27 21:35 UTC, jnm commented on kpi/deployment_backends/mock_backend.py
> +                detail=_('No submissions match the given `submission_ids`')
`_()` isn't imported. I'll fix it, but I'll also open a new issue about adding test code that reaches these lines.
Internal discussion: https://chat.kobotoolbox.org/#narrow/stream/4-Kobo-Dev/topic/Unused.20test.20code/near/104338

2022-04-27 21:53 UTC, jnm commented on kpi/deployment_backends/mock_backend.py
> +                detail=_('No submissions match the given `submission_ids`')
#3784

2022-04-27 21:56 UTC, jnm approved these changes

2022-05-11 14:43 UTC, merged