Fix synchronous export failure on insufficient permissions
kobotoolbox/kpi pull request #3700
Opened 2022-02-24 21:08 UTC by joshuaberetta

## Description

Return `404` if user does not have sufficient permissions to create a synchronous export.

## Related issues

closes #3699

2022-03-02 16:08 UTC, jnm requested changes

2022-03-02 16:08 UTC, jnm commented on kpi/mixins/export_object.py
> -            # returning a HTTP response
i think the comment is still valid: `get_export_object()` is called by a celery task as well as your new view.

my proposal would be to:
1. create a new exception class for this kind of permission-denied-during-export error
1. raise the exception here
1. catch the exception in the view and have the view return a 404
1. in the celery task, add a more specific exception handler [ref](https://github.com/kobotoolbox/kpi/blob/c2bb9d3066d6523f270df09283ecf62b4af21709/kpi/models/import_export_task.py#L110-L114) that catches this new exception, marks the job as failed, and sets an appropriate error message

i'll write a draft of this and ask you to review it

2022-03-04 15:26 UTC, jnm requested changes
thanks for the new tests :+1: the only thing i found was one stray `print` :smiley:

2022-03-04 15:26 UTC, jnm commented on kpi/tests/api/v2/test_api_exports.py
> +        print(synchronous_export_response.content.decode())
:grin:

2022-03-04 16:17 UTC, jnm commented on kpi/mixins/export_object.py
> -            # returning a HTTP response
https://github.com/kobotoolbox/kpi/pull/3713

2022-03-04 17:24 UTC, joshuaberetta commented on kpi/tests/api/v2/test_api_exports.py
> +        print(synchronous_export_response.content.decode())
lol 🤦

2022-03-05 02:25 UTC, merged