Add django allauth package
kobotoolbox/kpi pull request #4034
Opened 2022-09-30 16:00 UTC by bufke

2022-10-06 18:12 UTC, paulschreiber commented
See also work we have done in https://github.com/techmatters/kpi/tree/feat-terraso-auth

2022-10-07 17:53 UTC, bufke commented
Things for jnm to review

- General impact of the registration to allauth migration
- Email verification migration that assumes any existing email is verified and marks them for potential later intervention
- Account settings chosen in settings/base.py

2022-10-07 18:02 UTC, bufke commented
@noliveleger can you review only the MFA related parts of this? At this time, only password based login is important. Oauth mostly works but will be finalized in a future PR.

2022-10-24 20:08 UTC, JacquelineMorrissette requested changes

2022-10-24 20:20 UTC, JacquelineMorrissette commented
When setting up via kobo-install, if you don't setup STMP, it throws an error `[Open an interactive python shell in this frame] USError: [Errno 99] Cannot assign requested address` and I'm not sure that we want this to happen once it's merged in

2022-10-25 18:01 UTC, bufke commented on hub/views.py
> +#         return new_user
Forgot to implement! Fixed.

2022-10-25 18:06 UTC, bufke commented
Regarding SMTP, is there a stacktrace for that?

2022-10-25 18:44 UTC, bufke commented
@jnm do you think it makes sense to modify create_kobo_superuser to automatically verify the address? I'm going to implement it this way. Otherwise it's a barrier to getting up and running. Though it does reasonably error only after logging in and thus triggering the email, the install script is not the problem as far as I can tell.

2022-10-25 18:53 UTC, bufke commented
Jackie will work on porting over the domain list work, which is currently failing tests.

2022-11-28 19:41 UTC, bufke commented
Renamed https://github.com/kobotoolbox/kpi/pull/4163

2022-11-28 19:41 UTC, closed without merging