Update KoboToolbox logo in top bar menu and login page
kobotoolbox/kpi pull request #4172
Opened 2022-12-01 19:53 UTC by noliveleger

## Description

Make the logo KoboToolbox consistent all across the platform

## Additional info

Logo has been updated manually on [kf.kobotoolbox.org](https://kf.kobotoolbox.org) and [kobo.humanitarian.info](https://kobo.humanitarianresponse.info/)

2022-12-02 21:47 UTC, jnm requested changes
I'm admittedly rushing, but for me, this does not change the logo on the login page. I think that is being served from https://github.com/kobotoolbox/kpi/blob/b6249dcfedc3ca782cc86e49a88939bf0e637c1f/static/kobologo.svg (after being copied to `staticfiles` by `manage.py collectstatic`?), which is unchanged by this PR

2022-12-05 19:23 UTC, noliveleger commented
> I'm admittedly rushing, but for me, this does not change the logo on the login page. I think that is being served from https://github.com/kobotoolbox/kpi/blob/b6249dcfedc3ca782cc86e49a88939bf0e637c1f/static/kobologo.svg (after being copied to `staticfiles` by `manage.py collectstatic`?), which is unchanged by this PR

Indeed, when I try: 
```shell
# rm -rf "${KPI_SRC_DIR}/jsapp/fonts" && \
    rm -rf "${KPI_SRC_DIR}/jsapp/compiled" && \
    npm run copy-fonts && npm run build
    
# python manage.py collectstatic --noinput    
# rsync -aq --delete --chown=www-data "${KPI_SRC_DIR}/staticfiles/" "${NGINX_STATIC_DIR}/"
```

It does change the logo inside the app (`/static/compiled/kobologo..svg`), but not on the login page (`/static/kobologo.svg`)

2022-12-06 22:10 UTC, jnm commented
note to self: check that #4168 is resolved with this change

2022-12-06 22:37 UTC, jnm approved these changes

2022-12-06 22:37 UTC, merged