Custom Views: integrate endpoints into front-end
kobotoolbox/kpi pull request #4182
Opened 2022-12-07 13:20 UTC by magicznyleszek

## Description

## Notes for reviewer

Includes back-end code from `4081-regional-views` branch

Built atop `cleanup-projects-table` branch (PR #4167). Please change base branch to `feature/regional_projects` after that PR is merged.

## Related issues

Fixes #4059
Fixes #4060 
Fixes #4061 
Fixes #4062 
Fixes #4055

2022-12-16 13:51 UTC, noliveleger commented
@magicznyleszek back-end code is already reviewed and merged in `feature/regional_projects`

2023-01-13 21:15 UTC, p2edwards requested changes

2023-01-13 21:15 UTC, p2edwards commented on jsapp/js/projects/projectsTable/projectsTable.tsx
> +const SCROLL_PARENT_ID = 'projects-table-is-using-infinite_scroll-succesfully';
```suggestion
const SCROLL_PARENT_ID = 'projects-table-is-using-infinite_scroll-successfully';
```

2023-01-13 21:16 UTC, p2edwards commented on jsapp/scss/_colors.scss
> +/* DEPRECAED
edit: this file is removed entirely in [this PR](https://github.com/kobotoolbox/kpi/pull/4204) anyway

2023-01-16 12:11 UTC, magicznyleszek commented on jsapp/js/assetUtils.ts
>    }
Fixed :)

2023-01-16 12:11 UTC, magicznyleszek commented on jsapp/js/assetUtils.ts
> +    asset?.summary?.labels &&
Fixed :)

2023-01-16 12:15 UTC, magicznyleszek commented on jsapp/js/components/formSummary.es6
> +          if (this.state.chartPeriod === 'week') {subsPerDay = [0, 0, 0, 0, 0, 0, 0];} else {subsPerDay = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Good idea

2023-01-16 14:33 UTC, magicznyleszek commented on jsapp/js/projects/projectViews/constants.ts
>  };
I left these WIP constants to not lose these queries. But I made a GH issue with this list included, so I removed it now :)

2023-01-16 14:42 UTC, magicznyleszek commented on jsapp/js/projects/projectViews/constants.ts
>  };
https://github.com/kobotoolbox/kpi/issues/4212

2023-01-16 14:43 UTC, magicznyleszek commented on jsapp/js/projects/projectViews/projectsFilterEditor.tsx
> +      value: undefined,
I made a GH issue for this: https://github.com/kobotoolbox/kpi/issues/4214

2023-01-16 17:28 UTC, magicznyleszek commented on jsapp/js/projects/customViewRoute.tsx
> +      $.ajax({
👍

2023-01-16 17:43 UTC, p2edwards approved these changes

2023-01-19 13:20 UTC, magicznyleszek commented on jsapp/js/dataInterface.ts
> +  languages: Array<string | null>;
Languages are never `null`, if no languages are defined, we get empty array. It is possible to get `null` for some old code reasons I think. I'm pretty sure this list is the same as `asset.content.translations`, which is also `Array<string|null>`.

2023-01-19 13:46 UTC, merged