Misc. SSO front end changes
kobotoolbox/kpi pull request #4222
Opened 2023-01-19 23:35 UTC by duvld

## Description

1. Accessibility (a11y) allow using enter to submit email change
2. Add Resend and Delete buttons for new/unverified emails
3. Styling

## Related issues
Notion frontend changes

2023-01-20 16:10 UTC, bufke requested changes
The code works and improves the feature. The two api calls to resend email is clever and works. Please go ahead and merge after running prettier.

I'd like to see at least some error handling. Typing in a invalid email gives no error message. If this is a quick fix, go ahead and implement it. If not, please open a new issue about it.

2023-01-20 16:10 UTC, bufke commented on jsapp/js/account/security/email/emailSection.component.tsx
> +    deleteUnverifiedUserEmails().then(() => {
Ha I was expecting backend work here but this seems fine. The error handling is a bit trickier and we just aren't doing it right now. This is a comment and not a request for any change.

2023-01-20 16:10 UTC, bufke commented on jsapp/js/account/security/email/emailSection.component.tsx
> +                <label>
Please run through prettier, I'm seeing diffs when I apply it. I'm not sure how to enforce this on CI without running prettier on all code which IMO we should do so as to respect your time that I would rather have spent coding than doing things a bot could do.

2023-01-26 17:17 UTC, p2edwards approved these changes

2023-01-30 16:43 UTC, merged