Fix dangling comma in SSO signup form, minor language changes
kobotoolbox/kpi pull request #4391
Opened 2023-03-29 15:36 UTC by david-code

## Checklist

1. [x] If you've added code that should be tested, add tests
2. [x] If you've changed APIs, update (or create!) the documentation
3. [x] Ensure the tests pass
4. [x] Make sure that your code lints and that you've followed [our coding style](https://github.com/kobotoolbox/kpi/blob/master/CONTRIBUTING.md)
5. [x] Write a description of your work suitable for publishing on [our forum](https://community.kobotoolbox.org/tag/release-notes)
6. [x] Mention any related issues in this repository (as #ISSUE) and in other repositories (as kobotoolbox/other#ISSUE)
7. [x] Open an issue in the [docs](https://github.com/kobotoolbox/docs/issues/new) if there are UI/UX changes

## Description

Update SSO signup form to fix hanging comma when user's SSO account username not available. Minor language changes 

## Related issues

## Additional Comments

I'm not sure if we need to update the translations here. I seem to remember there being some documentation about this, but I can't find it now.

@bufke

2023-03-31 20:09 UTC, jnm requested changes
Thanks for the proposed contribution. I'll follow up about the wording change.

2023-03-31 20:09 UTC, jnm commented on kobo/apps/accounts/templates/socialaccount/signup.html
> +  {% else %}
If `username` is defined by the `blocktrans` tag, would this condition ever evaluate to true?

2023-03-31 20:20 UTC, paulschreiber commented on kobo/apps/accounts/templates/socialaccount/signup.html
> +  {% if username %}
```suggestion
  {% if form.username and form.username.value %}
```

2023-03-31 20:21 UTC, paulschreiber commented on kobo/apps/accounts/templates/socialaccount/login.html
> +    <p>{% blocktrans %}Log in to KoboToolbox with your {{ appname }} account.{% endblocktrans %}</p>
I agree this is redundant. Perhaps we could remove the middle paragraph.

2023-04-03 03:09 UTC, jnm commented on kobo/apps/accounts/templates/socialaccount/login.html
> +    <p>{% blocktrans %}Log in to KoboToolbox with your {{ appname }} account.{% endblocktrans %}</p>
After some internal discussion, we would like to keep your edits to the first and second lines but change the button to say just "LOG IN". While you're at it, if you wouldn't mind correcting "in to" to be "into", I'd be much obliged. I realize that mistake predated your PR.

2023-04-03 03:31 UTC, paulschreiber commented on kobo/apps/accounts/templates/socialaccount/login.html
> +    <p>{% blocktrans %}Log in to KoboToolbox with your {{ appname }} account.{% endblocktrans %}</p>
I have changed the button name. I believe "log in to" is correct. See [Stack Exchange discussion](https://english.stackexchange.com/questions/5302/log-in-to-or-log-into-or-login-to).

2023-04-04 17:19 UTC, jnm commented on kobo/apps/accounts/templates/socialaccount/login.html
> +    <p>{% blocktrans %}Log in to KoboToolbox with your {{ appname }} account.{% endblocktrans %}</p>
OK, I think the SE accepted answer is mostly a repudiation of "login" as a verb vs. "log in"—which I certainly agree with—but its nod to "log in to + noun" as more correct than "log into + noun" seems to neglect a lot of other valid points raised by the comments and other answers. Let's not spend any more time on it, though :ok_hand:

2023-04-05 13:32 UTC, merged