Status health redis
kobotoolbox/kpi pull request #4460
Opened 2023-06-06 19:58 UTC by bufke

## Description

Add cache (redis) check on service_health endpoint.

## Details

The health endpoint checks postgresql and mongo but not redis. That's inconsistent.

Redis is different in that it's possible to configure multiple redis's for cache and broker.

## Security Review

TDB

2023-06-23 19:22 UTC, jnm requested changes
Please rename the PR to something that uses the imperative mood, e.g. "Add Redis status checks to service health endpoint"

2023-06-23 19:22 UTC, jnm commented on kobo/apps/service_health/views.py
> +        'Broker': lambda: celery_app.backend.client.ping(),
To eliminate the Cypress-based login checker, we need a test for the Redis session store

2023-06-23 19:22 UTC, jnm commented on kobo/apps/service_health/views.py
> +            f"{service_name}: {service_message or 'OK'} {service_time:.3} seconds"
Please preserve the "thing *in* x seconds" convention

2023-06-23 23:46 UTC, jnm reviewed
@bufke LGTM except the CI failure looks legit?
```
=================================== FAILURES ===================================
__________________ ServiceHealthTestCase.test_service_health ___________________

self = <kobo.apps.service_health.test_service_health.ServiceHealthTestCase testMethod=test_service_health>

    @responses.activate
    def test_service_health(self):
        responses.add(responses.GET, 'http://enketo.mock/', status=200)
        responses.add(
            responses.GET, 'http://kobocat:8001/service_health/', status=200
        )
        res = self.client.get(self.url)
>       self.assertContains(res, "OK")

kobo/apps/service_health/test_service_health.py:16: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/django/test/testcases.py:462: in assertContains
    text_repr, real_count, msg_prefix = self._assert_contains(
/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/django/test/testcases.py:432: in _assert_contains
    self.assertEqual(
E   AssertionError: 500 != 200 : Couldn't retrieve content: Response code was 500 (expected 200)
----------------------------- Captured stderr call -----------------------------
ERROR:django.request:Internal Server Error: /service_health/
------------------------------ Captured log call -------------------------------
ERROR    django.request:log.py:224 Internal Server Error: /service_health/
```

2023-06-28 17:41 UTC, bufke commented
I don't know why it passed before, it seems the problem was with the mocked enketo/kc endpoints. Changed the test to use the urls from settings.

2023-07-03 14:50 UTC, jnm approved these changes
Thanks :+1:

2023-07-03 14:51 UTC, merged