Redirect away from Plans page when Stripe isn't enabled or no plans are available
kobotoolbox/kpi pull request #4545
Opened 2023-07-18 17:24 UTC by LMNTL

## Checklist

1. [ ] If you've added code that should be tested, add tests
2. [ ] If you've changed APIs, update (or create!) the documentation
3. [X] Ensure the tests pass
4. [X] Make sure that your code lints and that you've followed [our coding style](https://github.com/kobotoolbox/kpi/blob/master/CONTRIBUTING.md)
5. [X] Write a description of your work suitable for publishing on [our forum](https://community.kobotoolbox.org/tag/release-notes)
6. [ ] Mention any related issues in this repository (as #ISSUE) and in other repositories (as kobotoolbox/other#ISSUE)
7. [ ] Open an issue in the [docs](https://github.com/kobotoolbox/docs/issues/new) if there are UI/UX changes

## Description

Redirects users away from `/#/account/plan` if Stripe isn't enabled or there are no products available.

2023-08-09 21:25 UTC, srartese commented
A few notes that don't have anywhere specifically to go: 
- Check against the linter (I did leave one from previous work there about the any which is on my list to go back so feel free to ignore that one) 
- When testing there was a bug that I'm don't think is possible when live but I wanted to point out incase. I had multiple subscriptions on an account because of not updated stripe immediately which meant the banner was showing on both monthly and yearly.

2023-08-09 21:28 UTC, srartese requested changes

2023-08-09 21:28 UTC, srartese commented on jsapp/js/account/plan.component.tsx
>  import {BaseProduct} from 'js/account/subscriptionStore';
This isn't used anywhere

2023-08-09 21:28 UTC, srartese commented on jsapp/js/account/plan.component.tsx
>  import envStore, {FreeTierThresholds, FreeTierDisplay} from 'js/envStore';
FreeTierDisplay also looks to not be used anywhere

2023-08-10 17:21 UTC, LMNTL commented
>     * When testing there was a bug that I'm don't think is possible when live but I wanted to point out incase. I had multiple subscriptions on an account because of not updated stripe immediately which meant the banner was showing on both monthly and yearly.

Did you have a monthly and yearly subscription for the same plan? If so, that would be expected behavior - you have both types of subscription, and the frontend should reflect that. But if not, I have some bug-hunting to do 🙂

2023-08-16 20:41 UTC, srartese approved these changes
Yea I had two subscribed and I canceled one but it is still active technically. Sounds like its not a bug 🎉

2023-08-16 21:18 UTC, merged