WIP - 4473 block api with invalid password
kobotoolbox/kpi pull request #4573
Opened 2023-08-08 13:50 UTC by noliveleger

## Checklist

1. [ ] If you've added code that should be tested, add tests
2. [ ] If you've changed APIs, update (or create!) the documentation
3. [ ] Ensure the tests pass
4. [ ] Make sure that your code lints and that you've followed [our coding style](https://github.com/kobotoolbox/kpi/blob/master/CONTRIBUTING.md)
5. [ ] Write a description of your work suitable for publishing on [our forum](https://community.kobotoolbox.org/tag/release-notes)
6. [ ] Mention any related issues in this repository (as #ISSUE) and in other repositories (as kobotoolbox/other#ISSUE)
7. [ ] Open an issue in the [docs](https://github.com/kobotoolbox/docs/issues/new) if there are UI/UX changes

## Description

## Related issues

2023-08-18 15:08 UTC, JacquelineMorrissette requested changes

2023-08-30 05:25 UTC, jnm approved these changes

2023-08-30 05:25 UTC, jnm commented on kpi/serializers/current_user.py
> +            # `validated_password`. Let's consider it as True.
I'll revise this comment

2023-08-30 05:27 UTC, jnm commented on kobo/apps/accounts/tests/test_social_account.py
> +        with self.assertNumQueries(4):
I'd like to see this too, but `FuzzyInt` isn't a built-in thing and we never introduced any implementation of it into the code base. We could do it in a separate PR

2023-08-30 05:34 UTC, jnm commented on kobo/apps/accounts/tests/test_social_account.py
> +        with self.assertNumQueries(4):
Oh, whoops. I didn't realize you'd already added it :innocent:

2023-08-30 05:54 UTC, jnm requested changes
When I try to unset `validated_password ` in the admin interface, it blocks me saying that fields are required—but they shouldn't be:
![image](https://github.com/kobotoolbox/kpi/assets/2085013/edddf7e4-9765-4513-b2b2-692551ad07a9)

2023-08-30 06:27 UTC, jnm commented
Discovered by accident: if you become logged out somehow and then attempt to change your password, you get a 500 error: `NotImplementedError: Django doesn't provide a DB representation for AnonymousUser.` It comes from https://github.com/kobotoolbox/kpi/blob/db36eb086fb5fc4af856f99ed24bb7e4e4079b0a/kpi/serializers/current_user.py#L148

2023-08-30 18:05 UTC, noliveleger commented on kobo/apps/accounts/tests/test_social_account.py
> +        with self.assertNumQueries(4):
Yep, handled as a separate PR: #4606

2023-08-30 18:05 UTC, noliveleger commented on kobo/apps/organizations/tests/test_organizations_api.py
> +        with self.assertNumQueries(3):
Yep, handled as a separate PR: #4606

2023-08-30 18:05 UTC, noliveleger commented on kobo/apps/organizations/tests/test_organizations_api.py
> +        with self.assertNumQueries(5):
Yep, handled as a separate PR: #4606

2023-09-07 15:22 UTC, jnm approved these changes

2023-09-07 15:23 UTC, merged