Update CSP settings for GA4
kobotoolbox/kpi pull request #4582
Opened 2023-08-11 12:57 UTC by magicznyleszek

## Related issues

Fixes #4567

2023-08-11 16:27 UTC, bufke commented
@magicznyleszek would you like me to test this or just review the change. I see that when we upgraded to GA4, we switched our deployment method to GTM. If you describe your testing process to me, I'd be happy to consider if it was sufficient. If I should test it, then we should discuss internally how I can go about doing so and what access I may need. Or I suppose I could sign up for my own account and test with, as that workflow seems intended.

Are you confident that the google-analytics.com domain no longer needs allowed since switching to GA4 and GTM? The [documentation](https://developers.google.com/tag-platform/tag-manager/csp) is saying otherwise. See section Google Analytics 4 (Google Analytics)

2023-08-11 16:27 UTC, bufke requested changes
@magicznyleszek would you like me to test this or just review the change. I see that when we upgraded to GA4, we switched our deployment method to GTM. If you describe your testing process to me, I'd be happy to consider if it was sufficient. If I should test it, then we should discuss internally how I can go about doing so and what access I may need. Or I suppose I could sign up for my own account and test with, as that workflow seems intended.

Are you confident that the google-analytics.com domain no longer needs allowed since switching to GA4 and GTM? The [documentation](https://developers.google.com/tag-platform/tag-manager/csp) is saying otherwise. See section Google Analytics 4 (Google Analytics)

2023-08-11 16:32 UTC, magicznyleszek commented
@bufke I thought that since we are using GA4, and we are serving googletagmanager via script src, we only need this one thing:
<img width="878" alt="Screenshot 2023-08-11 at 18 30 42" src="https://github.com/kobotoolbox/kpi/assets/2521888/25b92cbe-d25d-4c4e-93ce-7d63f8b0993b">

2023-08-11 16:38 UTC, bufke commented
Isn't that saying you need to allow more right under the circle? But let us not speculate. Did you test this out or, if it's urgent and you don't have time, you can ask me to.

2023-08-11 20:34 UTC, bufke approved these changes
Approved pending testing

2023-08-11 20:34 UTC, bufke commented on kobo/settings/base.py
> +    # Taken from https://developers.google.com/tag-platform/tag-manager/csp#google_analytics_4_google_analytics
Good idea

2023-08-16 16:31 UTC, magicznyleszek commented
Note for future: testing this locally went like this:
1. set GA code in `./run.py --setup`
2. enabled CSP locally
3. turned off all possible blockers
4. confirmed that updated `Content-Security-Policy` appears in headers
5. confirmed that google script is being loaded
6. confirmed that google analytics page was in fact gathering data

2023-08-16 20:20 UTC, merged