Typescriptize permissions files
kobotoolbox/kpi pull request #4645
Opened 2023-09-19 19:43 UTC by magicznyleszek

## Checklist

1. [ ] If you've added code that should be tested, add tests
2. [ ] If you've changed APIs, update (or create!) the documentation
3. [ ] Ensure the tests pass
4. [ ] Make sure that your code lints and that you've followed [our coding style](https://github.com/kobotoolbox/kpi/blob/master/CONTRIBUTING.md)
5. [ ] Write a title and, if necessary, a description of your work suitable for publishing in our [release notes](https://community.kobotoolbox.org/tag/release-notes)
6. [ ] Mention any related issues in this repository (as #ISSUE) and in other repositories (as kobotoolbox/other#ISSUE)
7. [ ] Open an issue in the [docs](https://github.com/kobotoolbox/docs/issues/new) if there are UI/UX changes

## Description

Describe the outcome of your work here. A non-programmer who is familiar with KoboToolbox should be able to understand what you've written; more technical details can be added to the Notes section below. You may omit this if the title alone provides enough information. Both the title and this description will be published in the [release notes](https://community.kobotoolbox.org/tag/release-notes) on our forum.

## Notes

Describe what you've changed and why. This should allow the reviewer to understand more easily the scope of the PR. It's good to be thorough here.

## Related issues

Fixes #ISSUE
Blocked by #ISSUE
Part of #ISSUE

2023-10-10 19:07 UTC, p2edwards approved these changes

2023-10-10 19:38 UTC, p2edwards requested changes
Wait, there's a new problem that happens if you remove someone from the sharing section.

2023-10-11 21:36 UTC, magicznyleszek commented
@p2edwards I've fixed merge conflicts ;)

2023-10-12 15:39 UTC, p2edwards commented on jsapp/js/app.js
> -          <PermValidator />
@magicznyleszek Remove this too? 
```js
import PermValidator from 'js/components/permissions/permValidator';
```

2023-10-13 13:31 UTC, magicznyleszek commented
@p2edwards I've tested it more and found three things:
- added cache invalidation for `UserExistence` store, so that when someone checks for user that doesn't exist, and then at some point in near future that user is being created, check will return true value (instead of memoized one)
- removed unnecessary fallback for getting uid
- fixed a bug - `SharingForm` was adding listeners that were never removed, so when user visited multiple projects, in each opening sharing settings, the code was making multiple calls (each for visited project), and randomly (possibly based on API call response time) displaying permissions from one of them

2023-10-13 17:36 UTC, p2edwards commented on jsapp/js/users/userExistence.store.ts
> +    if (diffMins >= 3) {
What's all this conversion about?

```ts
const diffMins = Math.round(((diffMs % 86400000) % 3600000) / 60000);
if (diffMins >= 3) {
```

I have some problems with this code.

- It's hard to read.
- Rounding minutes before comparing `(diffMins >= 3)` makes 2½ minutes the limit instead of 3.
- The modulo `((…) % 3600000)` creates a brief window every hour where cache invalidation doesn't happen. 
- `% 86400000` is redundant with `% 3600000` (they divide evenly).

Suggestion:

- Compare the epoch time in milliseconds.

```ts
const limitMs = 3 * 60 * 1000; // 3 minutes
if (diffMs >= limitMs) {  /* invalidate cache */ }
```

```suggestion
    const limitMs = 3 * 60 * 1000; // 3 minutes
    if (diffMs >= limitMs) {
```

2023-10-16 12:44 UTC, magicznyleszek commented on jsapp/js/users/userExistence.store.ts
> +    if (diffMins >= 3) {
A lesson to not trust trusted stack overflow responses 😉

2023-10-16 12:49 UTC, p2edwards approved these changes

2023-11-07 21:14 UTC, p2edwards approved these changes

2023-11-07 21:15 UTC, merged