Paginate and cache submission data fetches for single processing view
kobotoolbox/kpi pull request #4854
Opened 2024-02-22 16:33 UTC by LMNTL

## Checklist

1. [ ] If you've added code that should be tested, add tests
2. [ ] If you've changed APIs, update (or create!) the documentation
3. [X] Ensure the tests pass
4. [X] Make sure that your code lints and that you've followed [our coding style](https://github.com/kobotoolbox/kpi/blob/master/CONTRIBUTING.md)
5. [X] Write a title and, if necessary, a description of your work suitable for publishing in our [release notes](https://community.kobotoolbox.org/tag/release-notes)
6. [ ] Mention any related issues in this repository (as #ISSUE) and in other repositories (as kobotoolbox/other#ISSUE)
7. [ ] Open an issue in the [docs](https://github.com/kobotoolbox/docs/issues/new) if there are UI/UX changes

## Description

Breaks up some frontend requests that could load up more submissions at once than necessary.

## Notes

Paginates the requests made from the Single Processing/NLP view . The Single Processing view now uses the same filter that's in use on the submission data table. The additional filters/sorts/etc. are appended to the URL, so that absolute URLs continue to work.

The Single Processing view wasn't made with pagination in mind, so this might be a bit clunky - if you have suggestions to streamline it, please let me know.

2024-03-14 16:22 UTC, magicznyleszek requested changes

2024-03-14 16:22 UTC, magicznyleszek commented on jsapp/js/router/routerConstants.ts
> +  FORM_PROCESSING: `${FORM_PROCESSING_BASE}/:qpath/:submissionEditId/:filters/:sort/:pageSize/:startIndex`,
Do you think there are any obstacles with changing it right now?

2024-03-14 16:22 UTC, magicznyleszek commented on jsapp/js/router/routerUtils.ts
> +      .replace('/:filters/:sort/:pageSize/:startIndex', '')
Or if we change it to a query, then we could avoid this problem

2024-03-14 16:22 UTC, magicznyleszek commented on jsapp/js/components/submissions/mediaCell.tsx
> +  startIndex: number;
(see `tableInfo` comment for `table.es6`)

2024-03-14 16:22 UTC, magicznyleszek commented on jsapp/js/components/submissions/table.es6
> +        sort: this.state.sort,
(see `tableInfo` comment above)

2024-03-14 16:22 UTC, magicznyleszek commented on jsapp/js/components/submissions/table.es6
> +                  startIndex={this.state.currentPage * this.state.pageSize}
(Sorry for spamming with all these `(see tableInfo comment for table.es6)` comments, but I wanted to check in how many places this would be used ;))

2024-04-11 15:46 UTC, magicznyleszek commented
I haven't found a task for it in Notion, so I've created one to make sure we don't loose this improvement :)

2024-10-17 19:36 UTC, jnm commented
We'll retain this code and review as a reference but not proceed on this path. Please see internal discussion at https://www.notion.so/kobotoolbox/NLP-Paginate-submission-data-fetches-to-support-large-projects-cdc3f18cbbb341eba652a3fd0c1fc779

2024-10-17 19:36 UTC, closed without merging