Bugfix/remove double asset filter
kobotoolbox/kpi pull request #5011
Opened 2024-07-15 18:21 UTC by rgraber

## Checklist

1. [ ] If you've added code that should be tested, add tests
2. [ ] If you've changed APIs, update (or create!) the documentation
3. [ ] Ensure the tests pass
4. [ ] Make sure that your code lints and that you've followed [our coding style](https://github.com/kobotoolbox/kpi/blob/master/CONTRIBUTING.md)
5. [ ] Write a title and, if necessary, a description of your work suitable for publishing in our [release notes](https://community.kobotoolbox.org/tag/release-notes)
6. [ ] Mention any related issues in this repository (as #ISSUE) and in other repositories (as kobotoolbox/other#ISSUE)
7. [ ] Open an issue in the [docs](https://github.com/kobotoolbox/docs/issues/new) if there are UI/UX changes

## Description

Describe the outcome of your work here. A non-programmer who is familiar with KoboToolbox should be able to understand what you've written; more technical details can be added to the Notes section below. You may omit this if the title alone provides enough information. Both the title and this description will be published in the [release notes](https://community.kobotoolbox.org/tag/release-notes) on our forum.

## Notes

Describe what you've changed and why. This should allow the reviewer to understand more easily the scope of the PR. It's good to be thorough here.

## Related issues

Fixes #ISSUE
Blocked by #ISSUE
Part of #ISSUE

2024-07-16 08:04 UTC, magicznyleszek commented
@rgraber let me know when this is done. I assigned myself as reviewer :)

2024-07-16 15:05 UTC, rgraber commented
> @rgraber let me know when this is done. I assigned myself as reviewer :)

Hi @magicznyleszek ! This is ready for review.

2024-07-18 21:31 UTC, magicznyleszek requested changes

2024-07-18 21:31 UTC, magicznyleszek commented on jsapp/js/projects/customViewStore.ts
> +
Unnecessary empty line :)

2024-07-18 21:33 UTC, magicznyleszek approved these changes

2024-07-19 13:45 UTC, merged