Fix error when deleting a user from admin interface
kobotoolbox/kpi pull request #5111
Opened 2024-09-16 13:35 UTC by noliveleger

## Description

Fix error `relation "logger_xform" does not exist ... ` when user is being deleted

## Notes

This PR uses monkey patching to replace a Django utility to remove models which have a relationship with User model but from other database. E.g. When user1 - User object - is deleted from KPI database, XForm related models should not be deleted in cascade within this transaction. They should be only when user1 is deleted from KoboCAT database.

2024-09-16 20:29 UTC, rgraber reviewed
One big question: is there any way to construct actual reverse sqls so we get the constraints/table back? I worry about having no way to reconstruct the tables if we need to revert the migration for some reason.

2024-09-16 21:32 UTC, noliveleger commented
> One big question: is there any way to construct actual reverse sqls so we get the constraints/table back? I worry about having no way to reconstruct the tables if we need to revert the migration for some reason.

@rgraber it is a really good question, but, IMO, in that case it is not worth it because the models have been removed from current release. In the previous release, they were a copy of KPI tables. If we had to revert to the previous release, we would apply migrations from `auth` and `django_digest` to restore the tables and their constraints. Then we would just need to copy the data from KPI (but it was auto synchronizing data).

2024-09-18 19:44 UTC, rgraber requested changes
Requests for more comments

2024-09-18 19:44 UTC, rgraber commented on kpi/utils/monkey_patching.py
> +        and (f.one_to_one or f.one_to_many)
Can you add a comment specifying that here and below is the actual new stuff, and the bit above comes directly from the original source code?

2024-09-18 19:44 UTC, rgraber commented on kobo/apps/openrosa/apps/api/migrations/0006_delete_digest_and_auth_token_table.py
> +        SELECT con.conname
More comments about what this does would be helpful

2024-09-18 19:45 UTC, rgraber commented
> > One big question: is there any way to construct actual reverse sqls so we get the constraints/table back? I worry about having no way to reconstruct the tables if we need to revert the migration for some reason.
> 
> @rgraber it is a really good question, but, IMO, in that case it is not worth it because the models have been removed from current release. In the previous release, they were a copy of KPI tables. If we had to revert to the previous release, we would apply migrations from `auth` and `django_digest` to restore the tables and their constraints. Then we would just need to copy the data from KPI (but it was auto synchronizing data).

That's still a little scary but as long as we have some kind of reversion plan we can go with it.

2024-09-19 12:56 UTC, rgraber approved these changes
LGTM

2024-09-19 21:35 UTC, merged