Task 869 group at fetch
kobotoolbox/kpi pull request #5113
Opened 2024-09-17 20:24 UTC by rgraber

## Checklist

1. [ ] If you've added code that should be tested, add tests
2. [ ] If you've changed APIs, update (or create!) the documentation
3. [ ] Ensure the tests pass
4. [ ] Make sure that your code lints and that you've followed [our coding style](https://github.com/kobotoolbox/kpi/blob/master/CONTRIBUTING.md)
5. [ ] Write a title and, if necessary, a description of your work suitable for publishing in our [release notes](https://community.kobotoolbox.org/tag/release-notes)
6. [ ] Mention any related issues in this repository (as #ISSUE) and in other repositories (as kobotoolbox/other#ISSUE)
7. [ ] Open an issue in the [docs](https://github.com/kobotoolbox/docs/issues/new) if there are UI/UX changes

## Description

Describe the outcome of your work here. A non-programmer who is familiar with KoboToolbox should be able to understand what you've written; more technical details can be added to the Notes section below. You may omit this if the title alone provides enough information. Both the title and this description will be published in the [release notes](https://community.kobotoolbox.org/tag/release-notes) on our forum.

## Notes

Describe what you've changed and why. This should allow the reviewer to understand more easily the scope of the PR. It's good to be thorough here.

## Related issues

Fixes #ISSUE
Blocked by #ISSUE
Part of #ISSUE

2024-09-26 20:01 UTC, noliveleger requested changes

2024-09-27 13:05 UTC, rgraber commented on kobo/apps/audit_log/tests/test_one_time_auth.py
> +                # try both v1 and v2
What do you mean? Isn't v1 just the openrosa endpoint?

2024-09-27 13:28 UTC, rgraber commented on kpi/fields/username_hyperlinked.py
> +class UsernameHyperlinkField(serializers.HyperlinkedRelatedField):
I like the idea of updating RelativePrefix... to allow it to take strings. Updating

2024-10-01 22:05 UTC, noliveleger commented on kobo/apps/audit_log/tests/test_one_time_auth.py
> +                # try both v1 and v2
@rgraber nope, they are two different things.

`OpenRosa` API implements three endpoints:

- `/formList`
- `/manifest`
- `/submission`

That's what Enketo and Collect are using to `POST` data. They are expecting these routes. 

`/api/v1/submissions` is a  DRF endpoint that users could use to `POST` data via API. 
IIRC, the former was calling a legacy django view before. It was two different part of code (which achieved the same thing). But now, they do call the same code 

```
/<username>/submission	kobo.apps.openrosa.apps.api.viewsets.xform_submission_api.XFormSubmissionApi	submissions
/api/v1/submissions	kobo.apps.openrosa.apps.api.viewsets.xform_submission_api.XFormSubmissionApi	submissions-list
/submission	kobo.apps.openrosa.apps.api.viewsets.xform_submission_api.XFormSubmissionApi	submissions
```

Having that said, none of them are `v2`. You cannot `POST` to `v2`.

2024-10-02 13:17 UTC, noliveleger approved these changes

2024-10-02 13:17 UTC, merged