feat(organizations): update owner filtering on projects table TASK-1335
kobotoolbox/kpi pull request #5362
Opened 2024-12-17 01:32 UTC by RuthShryock

### 🗒️ Checklist

1. [X] run linter locally
2. [X] update all related docs (API, README, inline, etc.), if any
3. [X] draft PR with a title `<type>(<scope>)<!>: <title> TASK-1234`
4. [X] tag PR: at least `frontend` or `backend` unless it's global
5. [X] fill in the template below and delete template comments
6. [X] review thyself: read the diff and repro the preview as written
7. [X] open PR & confirm that CI passes
8. [X] request reviewers, if needed
9. [ ] delete this section before merging

### 📣 Summary
Enable filtering by both the organization name and the owner's name when selecting 'Owner' as a filter on the projects table. 

## 💭 Notes 
Known issues (Olivier's notes from Notion task)

Because we are searching on both field at the same time (it would be too difficult to do conditional search on whether the organization is MMO). Returned results could be false positive. 
Example: 
Tino sees two projects on in “My Project” list 

- Project 1 owns by olivierleger the user 
- Project 2 owns by jnm the user, but filled out the registration form with  “leger inc” as his the organization. 

If Tino searches for “owner” which should contain “leger”, both projects will appear, even if Project 2 shows “jnm” as the owner.

### 👀 Preview steps

Feature/no-change template:
1. ℹ️ have account (someuser) and several projects 
2. have user (kobouser) with organization name (Some Org) share a project with your account 
3. have  user (anotheruser) who is part of an MMO (Kobo Inc) share a project with your account 
4. 🟡 notice that projects by **_someuser_** and **_kobouser_** have the owner name as the owner label, but projects by **_anotheruser_** have **_Kobo Inc_** as the owner label (not part of this pr but important)
5. ➡️  filter by "Owner" contains "user"
6. 🟢 notice that all projects are shown
7. ➡️  filter by "Owner" contains "kobo"
8. 🟢 notice that projects from **_kobouser_** and **_Kobo Inc_** are shown
9. ➡️  filter by "Owner" contains "some"
10. 🟢 notice that projects from **_someuser_** and **_kobouser_** are shown. (Even though **_kobouser_** is shown as the owner name, we are filtering by the organization name as well, more on false positive in Notes above).

2024-12-17 16:28 UTC, noliveleger requested changes

2024-12-17 16:28 UTC, noliveleger commented on jsapp/js/projects/projectViews/utils.ts
> +        .replace('<field>', 'search_field__owner_name')
Should be `search_field__owner_username`

2024-12-20 19:36 UTC, p2edwards commented on jsapp/js/projects/projectViews/utils.tests.ts
> +            'OR search_field__organization_name__icontains:"foo")',
in this update, it looks like "owner does not contain" was removed and "owner does contain" was added.

- does the frontend support **exact match** on owner name? if so, should there be a test for this one, too?
- (less important) should we add back the does not contain test?

2024-12-20 20:15 UTC, pauloamorimbr commented
Frontend looks good. My only issue here is that I have a user called `dd` and 2 projects that belong to me, but when filtering by Owner I just can't make the projects appear. Either using `d`, `dd` or `me`, they never show up.

If it's expected behavior (like if it needs at least 3 characters or something like that), then it seems it's good to go.

2024-12-20 21:14 UTC, pauloamorimbr approved these changes
LGTM! 👏🏻

2024-12-20 21:15 UTC, merged