feat(organizations): fix data and navigation flow when member updates themselves TASK-1354
kobotoolbox/kpi pull request #5393
Opened 2024-12-19 23:48 UTC by pauloamorimbr

### 🗒️ Checklist

1. [ ] run linter locally
2. [ ] update all related docs (API, README, inline, etc.), if any
3. [ ] draft PR with a title `<type>(<scope>)<!>: <title> TASK-1234`
4. [ ] tag PR: at least `frontend` or `backend` unless it's global
5. [ ] fill in the template below and delete template comments
6. [ ] review thyself: read the diff and repro the preview as written
7. [ ] open PR & confirm that CI passes
8. [ ] request reviewers, if needed
9. [ ] delete this section before merging

### 📣 Summary

### 📖 Description

### 👷 Description for instance maintainers

### 💭 Notes

### 👀 Preview steps

Bug template:
1. ℹ️ have an account and a project
2. do this
3. do that
4. 🔴 [on main] notice that this isn't anywhere BUT it should be here
5. 🟢 [on PR] notice that this is here

Feature/no-change template:
1. ℹ️ have account and a project
2. do this
3. do that
4. 🟢 notice that this is there
5. do that another thing
6. 🟢 notice that this changed like that

2024-12-23 17:04 UTC, p2edwards commented
Skimmed, will test soon.

2025-01-06 11:07 UTC, Akuukis requested changes
questions inline, didn't test. Also
- [ ] the title is confusing to have both "feat" and "fix" keywords in it, how about "feat(organizations): handle user removes itself flow" or similar?

2025-01-06 11:07 UTC, Akuukis commented on jsapp/js/account/organization/membersQuery.ts
> +      if (params?.isRemovingSelf) {
IMHO this hook can be simplified by removing the `isRemovingSelf` parameter and accessing variables within `onSettled` instead.
```ts
    onSettled: (_data, _error, username) => {
      if (session.currentLoggedAccount?.username === username) {
```

2025-01-06 11:07 UTC, Akuukis commented on jsapp/js/account/organization/membersQuery.ts
>      onSettled: () => {
perhaps use `onSuccess` instead? It would be confusing to get logged out on a failure to remove oneself.

2025-01-06 13:19 UTC, jamesrkiger commented on jsapp/js/account/organization/MemberRemoveModal.tsx
> +import router from 'jsapp/js/router/router';
unused imports

2025-01-06 14:11 UTC, jamesrkiger requested changes
Left a couple minor notes. On testing, I see the remaining issues from usage, but this is certainly an improvement. I will test again once you go through Kalvis' requested changes.

2025-01-08 14:56 UTC, pauloamorimbr commented on jsapp/js/account/organization/membersQuery.ts
> +      }
I'm adding that parameter there because the user, upon removal (self or not), will loose access to the members query, and react-query will try to refetch it, since it has done before, causing a error in the API call. 
I'm preventing that wrong call here by not running the invalidation. 

Right after this process the user is redirected to another view and the query is killed, but that only happens after the attempt to call the invalidation.

2025-01-08 15:12 UTC, pauloamorimbr commented on jsapp/js/account/organization/membersQuery.ts
> +      if (params?.isRemovingSelf) {
Really good one! 👏🏻

2025-01-08 18:01 UTC, pauloamorimbr commented
> Left a couple minor notes. On testing, I see the remaining issues from usage, but this is certainly an improvement. I will test again once you go through Kalvis' requested changes.

I changed it up a bit and seems like I got rid of the usage call on this.  🙌🏻 
Still, there are 2 tasks created related to this:
- migrate useUsage to react-query
- handle the flow for admin users who turn themselves into members

2025-01-09 12:31 UTC, jamesrkiger approved these changes
lgtm

2025-01-09 15:31 UTC, merged