Create endpoints to handle organization invitations
kobotoolbox/kpi pull request #5395
Opened 2024-12-20 15:00 UTC by rajpatel24

### 🗒️ Checklist

1. [ ] run linter locally
2. [ ] update all related docs (API, README, inline, etc.), if any
3. [ ] draft PR with a title `<type>(<scope>)<!>: <title> TASK-1234`
4. [ ] tag PR: at least `frontend` or `backend` unless it's global
5. [ ] fill in the template below and delete template comments
6. [ ] review thyself: read the diff and repro the preview as written
7. [ ] open PR & confirm that CI passes
8. [ ] request reviewers, if needed
9. [ ] delete this section before merging

### 📣 Summary

### 📖 Description

### 👷 Description for instance maintainers

### 💭 Notes

### 👀 Preview steps

Bug template:
1. ℹ️ have an account and a project
2. do this
3. do that
4. 🔴 [on main] notice that this isn't anywhere BUT it should be here
5. 🟢 [on PR] notice that this is here

Feature/no-change template:
1. ℹ️ have account and a project
2. do this
3. do that
4. 🟢 notice that this is there
5. do that another thing
6. 🟢 notice that this changed like that

2025-01-04 10:45 UTC, magicznyleszek commented
@rajpatel24 Wuld that whole invite object be present in `/api/v2/organizations/:organization_id/members/` in the `invite` property?

2025-01-04 10:53 UTC, magicznyleszek commented on kobo/apps/organizations/models.py
> +    RESENT = 'resent'
@rajpatel24 What's the difference between `in_progress` and `pending`?

2025-01-06 06:20 UTC, rajpatel24 commented
> @rajpatel24 Wuld that whole invite object be present in `/api/v2/organizations/:organization_id/members/` in the `invite` property? And I see you have `pending` status in there, and is this the same as `sent`?

@magicznyleszek No, the invite object would not be present there. I don't think it's necessary since `/api/v2/organizations/:organization_id/members/` is designed to list the members who are already part of the organization - those who have accepted the invitations and are now part of it.

The `pending` status is the same as `sent`. When the organization owner sends an invitation, the status of the invite will be set to `pending`.

2025-01-06 07:44 UTC, rajpatel24 commented on kobo/apps/organizations/models.py
> +    RESENT = 'resent'
@magicznyleszek As of now, we're not using `in_progress` as a status for organization invitations. I included it as a possible choice, along with `completed` and `failed`, in case the need arises in the future. Once @noliveleger  is back (probably today), I'll discuss this with him. Currently, when the organization owner sends an invitation, the status is set to `pending`. When the invitee accepts the invitation, the status changes to `accepted` in the `OrganizationInvitation` table.

Additionally, when a user accepts an invitation, we trigger an async task to transfer their projects to the organization. This is part of the existing functionality we're reusing for project transfers along with organization invitations. It uses its own `project-ownership/Invite` table with different statuses, which you might already be familiar with.

So, my question for @noliveleger  would be: when the project transfer is completed and the status in the `project-ownership/Invite` table is set to `completed`, do we also need to set the status to `completed` in the `OrganizationInvitation` table, or is the `accepted` state sufficient?

**To summarize**, the `/api/v2/organizations/:organization_id/invites/` API will currently have the following statuses: `pending`, `accepted`, `declined`, `cancelled`, `expired`, and `resent`.

If any changes occur regarding this, I'll make sure to update you right away.

2025-01-06 14:35 UTC, noliveleger commented on kobo/apps/organizations/models.py
> +    RESENT = 'resent'
@rajpatel24 , `accepted` would be enough for `OrganizationInvitation`.

2025-01-15 22:21 UTC, noliveleger requested changes

2025-01-15 22:21 UTC, noliveleger commented on kobo/apps/organizations/templates/emails/accepted_invite.txt
> +{% trans "Note: You will continue to have permissions to manage these projects until the user permissions are changed." %}
I don't think this sentence should be here since that's the sender who receives this message.
(Please fix HTML template too)

2025-01-15 22:21 UTC, noliveleger commented on kobo/apps/organizations/templates/emails/registered_user_invite.txt
> +{% trans "Hello," %}
Let's be a little more fancy,
If email has been sent to a username, let's use: `Hello <username>`
if email has been sent to a valid email with only one account, let's use: `Hello <username>`  
if email has been sent to a valid email with more than one account, let's use: `Hello <email>`  .

Then get rid of `(username: {{ recipient_username }}) ` in block below


What happens if invitation is sent to an email with multiple account? I don't see the template for that? The text is little bit different

2025-01-16 13:33 UTC, rajpatel24 commented on kobo/apps/organizations/templates/emails/registered_user_invite.txt
> +{% trans "Hello," %}
Sure, I've updated the template accordingly. 

Regarding the template for multiple accounts, it is included in the same template with the `has_multiple_accounts` condition. I’ve also updated some text for it.

2025-01-16 15:16 UTC, noliveleger requested changes

2025-01-16 15:16 UTC, noliveleger commented on kobo/apps/organizations/views.py
> +    def create(self, request, *args, **kwargs):
a->z :-)

2025-01-20 11:56 UTC, rajpatel24 commented on kobo/apps/organizations/views.py
> +    lookup_field = 'guid'
@noliveleger I tried to override the `guid` field from `django-organizations` with our `KpiUidField`, but the parent class’s `save()` method includes logic to set a unique ID if `guid` is absent. This prevents `KpiUidField` from saving the intended unique ID.

To address this, we might need to bypass the parent class’s save() method by doing:
```
def save(self, **kwargs):
    models.Model.save(self, **kwargs)
```

However, I’m concerned about potential trade-offs. Another option would be to remove the `guid` field and add a completely new `uid` field. What do you suggest?

2025-01-21 15:07 UTC, noliveleger commented on kobo/apps/organizations/views.py
> +    lookup_field = 'guid'
let's keep `guid` as-is. Forget about our `uid`.

2025-01-23 10:44 UTC, noliveleger commented on kobo/apps/organizations/models.py
> +                f"You're invited to join ##organization_name## organization"
Does not need to be an f-string anymore

2025-01-23 10:55 UTC, noliveleger commented on kobo/apps/organizations/models.py
> +        activate(sender_language)
It seems it would be better to use 

```python
with translation.override(sender_language):
    ...
```

instead of `activate(sender_language)`

Otherwise, everytime  we use `activate()` we should restore the current language when we are done with translations


```python
current_language = django.utils.translation.get_language()
activate(sender_language)
# do what you want with translations
activate(current_language)
```

2025-01-23 10:58 UTC, noliveleger commented on kobo/apps/organizations/models.py
> +        )
instead of hard-coding `'en'`, we should use either `settings.LANGUAGE_CODE` or `django.utils.translation.get_language()`


```python 
current_language = django.utils.translation.get_language()
# or current_language = settings.LANGUAGE_CODE
sender_language = self.invited_by.extra_details.data.get(
            'last_ui_language', current_language
)
```

2025-01-23 11:07 UTC, noliveleger requested changes

2025-01-23 11:07 UTC, noliveleger commented on kobo/apps/organizations/models.py
> +            ).replace('##organization_name##', organization_name),
You could use your utility `replace_placeholders()`

2025-01-23 11:07 UTC, noliveleger commented on kobo/apps/organizations/serializers.py
> +    @void_cache_for_request(keys=("organization",))
I'm surprised the linter did not catch it but use single quotes 🙏 .

2025-01-23 11:07 UTC, noliveleger commented on kobo/apps/organizations/tests/test_organization_invitations.py
> +        ('external', status.HTTP_403_FORBIDDEN)
I think it should 404 for external. We don't want to reveal the existence of the organization to external.

2025-01-23 11:07 UTC, noliveleger commented on kobo/apps/organizations/tests/test_organization_invitations.py
> +        ('external', status.HTTP_403_FORBIDDEN)
I think it should 404 for external. We don't want to reveal the existence of the organization to external.

2025-01-23 15:39 UTC, rajpatel24 commented on kobo/apps/organizations/models.py
> +            ).replace('##organization_name##', organization_name),
Done. Also I have moved the utility function to a new file, as it is a generic utility not specific to the organizations app.

2025-01-24 07:55 UTC, merged